[package]
name = "gubert"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gio = "0.17.9"
glib = "0.17.9"
gtk = "0.17.1"
anyhow = "1.0.71"
tokio = { version = "1.28.1", features = ["full"] }
dirs = "5.0.1"
rs-llama-cpp = "0.1.25"
